version: '3.1'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=userdb
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
